spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# Spring boot 1.4+ 需要加上以下配置
security:
  basic:
    enabled: false
management:
  security:
    enabled: false